name: check_run

on:
  check_run:

jobs:
  check_run:
    runs-on: ubuntu-latest
    steps:
    - name: Echo github context
      continue-on-error: true
      run: echo '${{ toJson(github.event) }}' || true