name: workflow_run

on:
  workflow_run: 
    workflows: [abaplint]

jobs:
  workflow_run:
    runs-on: ubuntu-latest
    steps:
    - name: Echo github context
      continue-on-error: true
      run: echo '${{ toJson(github.event) }}' || true
